// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iphluakvvklyvymwhfxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwaGx1YWt2dmtseXZ5bXdoZnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNDg4NzAsImV4cCI6MjA4NTYyNDg3MH0.8YeaPErLX3vG0QzphQwB_40bn3v-FZI7FleTjOY1zbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});